### ISSUE TITLE
s.ios.deployment_target

### ISSUE THREAD

**Issue by jovanborne** [BrianCorbin/SwiftRangeSlider#1]
Hello Brian,

Is s.ios.deployment_target set to 9.0 really required for something in SwiftRangeSlider? If not, I'm sure that some projects still want to support older iOS versions, at least 8.4, so maybe we can change 9.0 to 8.4 in s.ios.deployment_target?

Best Regards?

**Comment by BrianCorbin** [comment]
Hey Jovan,

it should work fine on an 8.4 deployment! I seem to have incorrectly marked it as 9.0+. I’ll change that, thanks for the email! Hope you’re enjoying using the pod. Lemme know if you have any suggestions or if you’d like to see anything specifically :)

Brian

**Comment by brod-ie** [comment]
Any update on this? Currently importing manually

**Comment by BrianCorbin** [comment]
Thanks, @brod-ie, I accepted your merge request! My bad it's taken so long to get this fix in, been super busy with other projects... Enjoy!
