### ISSUE TITLE
Add Property, KnobAnchorPosition to mimic the default UISlider.

### ISSUE THREAD

**Issue by why2pac** [BrianCorbin/SwiftRangeSlider#13]
I sugget adding a new property to mimic the default UISlider. Currently SwiftRangeSlider `Knob` anchor position is middle aligned, In constrast, the default UISlider anchor position is inside aligned.

Half of the `Knob` size (it is equal to radius) will be exceed the bounds.

It would be better library, if KnobAnchorPosition property added.

**Comment by BrianCorbin** [comment]
I see your point, I will include this fix in the next round of changes!
