### ISSUE TITLE
Range Slider is not updating after setting Constrants in IB

### ISSUE THREAD

**Issue by swapnilcelusion** [BrianCorbin/SwiftRangeSlider#18]

**Comment by BrianCorbin** [comment]
Could you provide a little more detail? Thanks!

**Comment by vipinjohney** [comment]
I think I am facing the same issue. I had set the layout constraints for the view custom classed to RangeSlider. But when I run on the device the layout is not updated until I start sliding.
Actually the custom view is in the correct position as per the layout, but the slider is some issue falling into that layout. See the images. 
The grey portion in the image is actually the size of the custom view. 2 nd image is after I do a slide.

<img width="428" alt="screen shot 2017-08-03 at 9 09 07 pm" src="https://user-images.githubusercontent.com/2149948/28930276-162c67d2-7890-11e7-8fd6-fef2d0dcacff.png">
<img width="425" alt="screen shot 2017-08-03 at 9 09 24 pm" src="https://user-images.githubusercontent.com/2149948/28930277-162dab38-7890-11e7-87cc-a77529c1a45d.png">

**Comment by BrianCorbin** [comment]
Could you post source code for your implementation? I'll work on fixing this ASAP.

**Comment by swapnilcelusion** [comment]
Ok..sure

**Comment by BrianCorbin** [comment]
I've realized the issue is related to the rangeSlider not automatically updating its layer frames and positions upon auto layout laying out and sizing its subviews. The workaround for this is provided in the README.

For reference, in the function ```viewDidLayoutSubviews()``` you must call ```.updateLayerFramesAndPositions()``` on any range sliders you have present.
