### ISSUE TITLE
Stacked knobs get stuck at minimumValue.

### ISSUE THREAD

**Issue by dsoike** [BrianCorbin/SwiftRangeSlider#20]
If minimumDistance == 0, knobs can have the same value and become stacked. 

If the knobs become stacked at the minimumValue, they _get stuck_ and cannot be moved.

Not a problem mid-track or at the maximumValue.

![img_5372](https://cloud.githubusercontent.com/assets/7273143/26269473/95db7540-3ca9-11e7-8c0f-b48b90c130dc.PNG)

**Comment by BrianCorbin** [comment]
Hmm, I'm not able to reproduce this issue. Could you provide a bit more detail for reproducing the issue?
