### ISSUE TITLE
Add Step property

### ISSUE THREAD

**Issue by bull-xu-stride** [BrianCorbin/SwiftRangeSlider#3]
If possible, can we add a Step property to this awesome slider to control the minimum movement of the user's touch? For example, if the Step is 0.05, each time the deltaValue is at least 0.05 or a multiple of 0.05. A sample of this is the minuteInterval property of NSDatePicker to specify the minute increments.

**Comment by BrianCorbin** [comment]
Working on it! Will have updates soon.

**Comment by BrianCorbin** [comment]
Sorry for the lack of updates on this issue. Finally resolved a Swift3 issue with cocoapods and am now able to resume development on the pod! Will make this a priority.

**Comment by BrianCorbin** [comment]
Although this is not the ideal solution, it may be quicker if you try something like [this](http://stackoverflow.com/questions/6370342/implementing-steps-snapping-uislider) or [this](http://stackoverflow.com/questions/2519460/uislider-with-increments-of-5). I will come back to this as soon as possible!

**Comment by BrianCorbin** [comment]
I've added step value functionality. Apologies for the (very long) delay!
