### ISSUE TITLE
Add Min Distance

### ISSUE THREAD

**Issue by brod-ie** [BrianCorbin/SwiftRangeSlider#4]
This, combined with [adding a step property](https://github.com/BrianCorbin/SwiftRangeSlider/issues/3), would allow upper and lower sliders to be kept apart by a threshold.

An example would be an age range slider with a minimum gap of 4 years.

**Comment by BrianCorbin** [comment]
Working on it! Will have updates soon.

**Comment by BrianCorbin** [comment]
Sorry for the lack of updates on this issue. Finally resolved a Swift3 issue with cocoapods and am now able to resume development on the pod! Will make this a priority.

**Comment by BrianCorbin** [comment]
Added this in the next update (0.5.1). There are still some issues with setting it programmatically / from the storyboard that will need to be fixed, but hopefully this is sufficient for now.
