### ISSUE TITLE
Layer crashes when minimumValue and maximumValue are same 

### ISSUE THREAD

**Issue by bull-xu-stride** [BrianCorbin/SwiftRangeSlider#6]
NaN error:

  func positionForValue(value: Double) -> Double {
    return Double(bounds.width - thumbWidth) \* (value - minimumValue) /
      (**maximumValue - minimumValue**) + Double(thumbWidth / 2.0)
  }

**Comment by BrianCorbin** [comment]
Fixed in next update (0.5.1). Now returns 0 when maximum and minimum value are the same
