### ISSUE TITLE
Pod not updated for Swift 3

### ISSUE THREAD

**Issue by vinod1879** [BrianCorbin/SwiftRangeSlider#7]
The Podspec specifies version `1.4.2`, but the latest version on Cocoapods appears to be 1.3.3. 
Also, the code installed via Cocoapods is the Swift 2.2 version, and does not contain the Swift 3 upgrade.

**Comment by BrianCorbin** [comment]
I am aware this is an issue. I'm still having difficulty getting it to successfully lint when I trunk the new version. I'm working on porting it to Swift 3 right now.

**Comment by donpironet** [comment]
+1 same problem

**Comment by BrianCorbin** [comment]
Still having issues with Swift3 and cocoa pods, but I'm working on a fix. Sorry this is taking so long.

**Comment by franiis** [comment]
Hi, any update on Swift 3 support?

**Comment by BrianCorbin** [comment]
Hey! I've gotten Swift 3 support done. It should be live on cocoapods as soon as they update their repo. New version is now '0.5.0'. Thanks for hanging in there with me guys!
