### ISSUE TITLE
Thumb layers stuck after moving the upperThumbLayer to be same as lowerThumbLayer

### ISSUE THREAD

**Issue by bull-xu-stride** [BrianCorbin/SwiftRangeSlider#8]
Set min = lower = 0, max = upper = 100. Move upper to 0, the thumb layers now stuck on 0 position. 

![image](https://cloud.githubusercontent.com/assets/12520500/19671163/84dae9c6-9ab8-11e6-893c-99c6345064ce.png)

LINE 193 need to change (instead of checking from lower thumb, there should be a var to keep what's the last highlighted thumb)

**Comment by BrianCorbin** [comment]
Fixed, coming in the next version (0.5.1)
